<?php
  session_start();
?>

<head>
    <link rel="stylesheet" href="../css/style.css">
</head>

  <nav>
      <div class="wrapper">
        <ul>
          <li><a href="../index.php">Home</a></li>
          <li><a href="../topics.php">Topics</a></li>
          <?php
            if(isset($_SESSION["useruid"])) {
              echo "<li><a href='../includes/logout.inc.php'>Logout</a></li>";
            }
            else {
              echo "<li><a href='../signup.php'>Sign Up</a></li>";
              echo "<li><a href='../login.php'>Log In</a></li>";
            }
          ?>
        </ul>
      </div>
    </nav>

<html lang="en">
<head>
<title>CSS Template</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}

header {
  background-color: #666;
  padding: 2px;
  text-align: center;
  font-size: 35px;
  color: white;
}

nav {
  -webkit-flex: 1;
  -ms-flex: 1;
  flex: 1;
  background: #ccc;
  padding: 20px;
}

article {
  -webkit-flex: 3;
  -ms-flex: 3;
  flex: 3;
  background-color: #f1f1f1;
  padding: 10px;
}

}
</style>
</head>
<body>

<header>
  <h2>Chapter 5 - Output Devices</h2>
</header>
  
  <article>
    <h1>Output Devices</h1>
    <p>Monitors is an electronic visual computer display that includes a screen, circuitry and the case in which that circuitry is protected. It displays images and videos.</p>
    <p>Printers is a device that accepts text and graphic output from a computer and transfers the information to paper.</p>
    <p>Projectors takes images generated by a computer and reproduces them by projection onto a screen, wall, or another surface, for example, you could use a projector to show a presentation on a large screen so that everyone in the room can see it.</p>
    <p>Speakers connects to a computer to generate sound. The signal used to produce the sound that comes from a computer speaker is created by the computer's sound card.</p>
    <p>Actuators is a device that uses a form of power to convert a control signal into mechanical motion. From electric door locks in automobiles, actuators are all around us.</p>
  </article>
</section>

</body>
</html>